- name: Install packages
  apt:
    pkg: "{{ packages }}"
    update_cache: yes
    state: latest

- name: Change apache port
  shell: sed -i "s/80/{{apache_port}}/" /etc/apache2/ports.conf

- name: Restart apache to avoid conflict with nginx
  service: name=apache2.service state=restarted enabled=yes

- name: Install nginx
  apt: name=nginx state=latest

- name: Change nginx config
  copy: src=default dest=/etc/nginx/sites-enabled
  notify: Restart nginx

- name: Correct apache config
  shell: cat /vagrant/initial_deploy/files/apache.txt >> /etc/apache2/apache2.conf

- name: PHP repo addition
  shell: echo "deb https://debian.octopuce.fr/snapshots/sury-php/20220630/ stretch main" | tee /etc/apt/sources.list.d/php.list && wget -qO - https://debian.octopuce.fr/sury-php/apt.gpg | apt-key add -

- name: PHP installation
  apt:
   update_cache: yes
   pkg: php{{php_version}}


- name: Choose php{{php_version}} as default
  shell:  echo "/usr/bin/php{{php_version}}" | update-alternatives --config php

- name: Save php version into variable
  shell: php -v | awk '{print $1, $2}' | head -n 1
  register: result

- name: Move files to www/html
  copy: src=/vagrant/code/display.php dest=/var/www/html


- name: Generate index.html
  template: src=/vagrant/code/index.j2 dest=/var/www/html/index.html

- name: Restart apache
  service: name=apache2.service state=restarted enabled=yes
